### ISSUE TITLE
can't do any DOM manipulation before fingering the Ifram event

### ISSUE THREAD

**Issue by shadyshrif** [vincepare/iframeTracker-jquery#15]
Normally my Iframe contains links. I want to catch the Iframe click event (which will open an external link) to show a message to user before opening the link. 

`
                $('#myFrame').iframeTracker({
                    blurCallback: function () {
                        $('#WelcomeMessage').modal('show');
                    }
                });
`

The Iframe event always triggers before showing the message.

I'm using Version 50.0.2661.66 beta-m (64-bit)

**Comment by vincepare** [comment]
Can you provide a live example (using https://jsfiddle.net/ or http://jsbin.com/) ?

`.modal` is not native jQuery, which plugin are you using ?

**Comment by shadyshrif** [comment]
Actually I'm tracking google ads, I tried to make any DOM change before the ad opens but It fails. forget about modal and try to do any change in DOM before the ad link opens.

**Comment by vincepare** [comment]
Unfortunately, I can't help with so little information. I do not even know if you are using the old adsense code or the new asynchronous code. Please provide a live example.

I tried to do some DOM manipulation like this :

```javascript
jQuery(document).ready(function($){
	$('#iframe_dummyads iframe').iframeTracker({
		blurCallback: function(){
			$('span.brand').append(" - DOM append");
			$('<div>').html("New div").insertAfter($('#wrap'));
		}
	});
});
```

And it works fine with the old adsense code (DOM is modified while the ads target link is opened in a new tab). It doesn't work with the async adsense code because the ads is not yet available at DOM ready. But I can make it work by binding iframeTracker after adsense rendering.

I'm testing on :
```
Google Chrome	50.0.2661.94 (Build officiel) m (32 bits)
Révision	0c319c380220abe3daf0277e40a2d0b22a7c4550-refs/branch-heads/2661@{#645}
```
