### ISSUE TITLE
Firefox - click not detected if pointer is in iFrame before document ready

### ISSUE THREAD

**Issue by nicStuff** [vincepare/iframeTracker-jquery#19]
With many empiric tests I've found out that if the mouse pointer is in the iframe area by the time document ready is triggered, all the clicks in the iframe won't get tracked.

In Chrome this doesn't happen, i.e. the clicks are still tracked.

At first glance this has to do with peculiarities of how a browser triggers windows blur, but it would be great to find a way to circumnvent this limitation.

**Comment by vincepare** [comment]
I was not able to reproduce this bug following the the description you have made.

Here is what I have : http://jsfiddle.net/g6z5nw4x/2/ ([result](http://fiddle.jshell.net/g6z5nw4x/2/show/)). None of the iframe clicks before DOM ready are tracked. Tracking only starts working after DOM ready, on Firefox and Chrome (63).

Can you tell which browser and jQuery version you are using, and provide a live example (use tools like [jsbin](https://jsbin.com), [jsfiddle](https://jsfiddle.net) or [codepen](https://codepen.io/)) ?

**Comment by vincepare** [comment]
Assuming your are talking about the fact that when the mouse cursor is inside a tracked iframe when DOM ready is fired, no click will be tracked **until the mouse cursor leave the iframe** (but then, all is fine, tracking works).

This is the expected behavior because iframeTracker ignore which iframe is hover while the mouse cursor has not yet crossed any iframe boundary.
